language: node_js
node_js:
  - 12
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_url: github.com
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: public
  fqdn: cloudnativereference.dev
  on:
    branch: master
